config/routes.rb
Rails.application.routes.draw do
  resources :horas_complementares do
    collection do 
      get 'carregar_atividades_categoria'
    end
  end
  # get 'horas_complementares/index'
  # post 'horas_complementares/create'
  # post 'horas_complementares/update'
  get 'pessoas/index'
  get 'pessoas/cadastro_final'
  get 'pessoas/perfil'
  get 'pessoas/editar_perfil'
  post 'pessoas/cadastrar'
  post 'pessoas/editar'
  resources :pessoas do
  end

  get 'atividades/index'

  get 'categorias/index'

  get 'cursos/index'

  get 'campus/index'

  get 'dashboards/index'
  get 'dashboards/categoria'
  get 'dashboards/download_anexo'
  get 'dashboards/deletar_hora_complementar'

  devise_for :usuarios
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'dashboards#index'
end

app/models/pessoa.rb
class Pessoa < ApplicationRecord
  belongs_to :campu
  belongs_to :curso
  belongs_to :usuario
  has_many :horas_complementares
  
  validates_uniqueness_of :matricula, conditions: -> { where(ativo: true) }

  mount_uploader :foto, FotoUploader

end

app/controllers/pessoas_controller.rb
class PessoasController < ApplicationController
  def index
  end

  def cadastro_final
    if !session[:pessoa].blank?
      flash[:notice] = 'Você já completou seu cadastro!'
      redirect_to pessoas_perfil_path
    else
    	@cursos = Curso.where(ativo: true).order(:nome)
      render layout: 'empty'
    end
  end

  def cadastrar
    @cursos = Curso.where(ativo: true).order(:nome)

  	@pessoa = Pessoa.new
  	@pessoa.nome = params[:nome]
  	@pessoa.apelido = params[:apelido]
  	@pessoa.matricula = params[:matricula]
  	@pessoa.curso_id = params[:curso]
    @pessoa.campu_id = Curso.find(params[:curso]).campu.id
  	@pessoa.contato = params[:contato]
  	@pessoa.usuario_id = current_usuario.id
  	@pessoa.foto = params[:foto]
  
  	if @pessoa.save
      session[:pessoa] = @pessoa.id
      redirect_to dashboards_index_path
    else
      flash[:notice] = 'Número de matricula já existente'
      redirect_to pessoas_cadastro_final_path
    end
  
  end

  def perfil
    @pessoa = Pessoa.find(session[:pessoa])
    @horas_realizadas = @pessoa.horas_complementares.where(ativo: true).sum('quantidade_horas')
    @horas_totais = @pessoa.curso.carga_atividades_complementares
  end

  def editar_perfil
    @pessoa = Pessoa.find(session[:pessoa])
    @cursos = Curso.where(ativo: true).order(:nome)
  end

  def show
  end

  def update
    pessoa = Pessoa.find(session[:pessoa])
    pessoa.update(nome: params[:pessoa][:nome], apelido: params[:pessoa][:apelido], matricula: params[:pessoa][:matricula], curso_id: params[:pessoa][:curso], campu_id: Curso.find(params[:pessoa][:curso]).campu_id, contato: params[:pessoa][:contato], foto: params[:pessoa][:foto])
    flash[:notice] = 'Perfil atualizado com sucesso!'
    redirect_to pessoas_perfil_path
  end
end

app/helpers/pessoa_helper.rb
module PessoaHelper
end

app/views/pessoas/cadastro_final.html.erb
<div class="container-default">
	<div class="container-header">
		<div class="row">
			<div class="col-1 col-sm-2 col-md-2 col-lg-2" style="padding: 0; padding-left: 3%;">
				<%= link_to(destroy_usuario_session_path, method: :delete, class: 'link-back') do %>
					<i class="fa fa-arrow-left icon-size"> </i>
				<% end %>
			</div>
			<div class="col-10 col-sm-10 col-md-7 col-lg-7" style="padding: 0;">
				<h2> Concluir Cadastro </h2>
			</div>
		</div>
	</div>

	<div class="container-body">
		<%= form_tag({controller: 'pessoas', action: 'cadastrar'}, :multipart => true) do %>
			<div class="input-field">
				<%= label_tag :matricula, 'Matrícula *' %><br>
				<%= number_field_tag :matricula, nil, class: 'input-form matricula', required: true %>
			</div>

			<div class="input-field">
				<%= label_tag :nome, 'Nome Completo *' %><br>
				<%= text_field_tag :nome, nil, class: 'input-form', required: true %>
			</div>

			<div class="input-field">
				<%= label_tag :apelido, 'Como gostaria de ser chamado? *' %><br>
				<%= text_field_tag :apelido, nil, class: 'input-form', required: true %>
			</div>

			<div class="input-field">
				<%= label_tag :curso, 'Curso *' %><br>
				<%= select_tag(:curso, options_for_select(@cursos.collect {|c| ["#{c.nome} - #{c.campu.cidade if !c.campu.blank?}", c.id]}), {prompt: 'Selecione uma opção', class: 'input-form', required: true}) %>
			</div>

			<div class="input-field">
				<%= label_tag :contato, 'Contato *' %><br>
				<%= text_field_tag :contato, nil, class: 'input-form celular', required: true %>
			</div>

			<div class="input-field">
				<%= label_tag :foto, 'Foto de Perfil' %><br>
				<label class="input-form" style="padding-left: 90px; padding-top: 7px;">
                  <div id="count">
                    <i class="fa fa-camera" aria-hidden="true"></i> Foto
                  </div>
                  <%= file_field_tag :foto, accept: 'image/jpg, image/jpeg, image/png',id: 'file',class: 'input-file' %>
                </label>
			</div>

			<%= button_tag(class: 'btn btn-purple') do %>
				SALVAR
			<% end %>
		<% end %>
	</div>
</div>

<%= stylesheet_link_tag 'pessoas' %>
<%= javascript_include_tag 'pessoas' %>

<script type="text/javascript">
	<% if !flash[:notice].blank? %>
		alertComplete("<%= flash[:notice] %>");
	<% end %>
	
	$("input:file").change(function (){
	    var fileName = $(this).val();
    	if (fileName){
      		if(fileName ==  document.getElementById("file").value){
        		document.getElementById("count").innerHTML = "<span class='badge badge-purple'>1</span> Foto";
      		}
    	}
    });
	$(".matricula").mask('999999');
    $(".celular").mask('(99) 99999-9999');
	
</script>

app/views/pessoas/editar_perfil.html.erb
<div class="container-default">
	<div class="container-header">
		<div class="row">
			<div class="col-1 col-sm-2 col-md-2 col-lg-2" style="padding: 0; padding-left: 3%;">
				<%= link_to(pessoas_perfil_path, class: 'link-back') do %>
					<i class="fa fa-arrow-left icon-size"> </i>
				<% end %>
			</div>
			<div class="col-10 col-sm-10 col-md-7 col-lg-7" style="padding: 0;">
				<h2> Editar Cadastro </h2>
			</div>
		</div>
	</div>

	<div class="container-body">
		<%= form_for(@pessoa, :multipart => true, method: :put) do |f| %>
			<div class="input-field">
				<%= f.label :matricula, 'Matrícula *' %><br>
				<%= f.number_field :matricula, class: 'input-form matricula', required: true %>
			</div>

			<div class="input-field">
				<%= f.label :nome, 'Nome Completo *' %><br>
				<%= f.text_field :nome, class: 'input-form', required: true %>
			</div>

			<div class="input-field">
				<%= f.label :apelido, 'Como gostaria de ser chamado? *' %><br>
				<%= f.text_field :apelido, class: 'input-form', required: true %>
			</div>

			<div class="input-field">
				<%= f.label :curso, 'Curso *' %><br>
				<%= f.select(:curso, options_for_select(@cursos.collect {|c| ["#{c.nome} - #{c.campu.cidade if !c.campu.blank?}", c.id]}, selected: @pessoa.curso_id), {prompt: 'Selecione uma opção'}, {class: 'input-form', required: true}) %>
			</div>

			<div class="input-field">
				<%= f.label :contato, 'Contato *' %><br>
				<%= f.text_field :contato, class: 'input-form celular', required: true %>
			</div>

			<div class="input-field">
				<%= f.label :foto, 'Foto de Perfil' %><br>
				<label class="input-form" style="padding-left: 90px; padding-top: 7px;">
                  <div id="count">
                    <i class="fa fa-camera" aria-hidden="true"></i> Foto
                  </div>
                  <%= f.file_field :foto, accept: 'image/jpg, image/jpeg, image/png',id: 'file',class: 'input-file' %>
                </label>
			</div>

			<%= button_tag(class: 'btn btn-purple') do %>
				SALVAR
			<% end %>
		<% end %>
	</div>
</div>

<%= stylesheet_link_tag 'pessoas' %>
<%= javascript_include_tag 'pessoas' %>

<script type="text/javascript">
	<% if !flash[:notice].blank? %>
		alertComplete("<%= flash[:notice] %>");
	<% end %>
	
	$("input:file").change(function (){
	    var fileName = $(this).val();
    	if (fileName){
      		if(fileName ==  document.getElementById("file").value){
        		document.getElementById("count").innerHTML = "<span class='badge badge-purple'>1</span> Foto";
      		}
    	}
    });
	$(".matricula").mask('999999');
    $(".celular").mask('(99) 99999-9999');
	
</script>

app/views/pessoas/index.html.erb
<h1>Pessoa#index</h1>
<p>Find me in app/views/pessoa/index.html.erb</p>

app/views/pessoas/perfil.html.erb
<div class="container-default">
	<div class="container-header">
		<div class="row">
			<div class="col-12 col-sm-12">
				<h2> Perfil </h2>
			</div>
		</div>
	</div>
	<div class="container-body">
		<div class="row">
			<div class="col-10">
				<%= image_tag((!@pessoa.foto.blank?) ? @pessoa.foto.url : 'avatar.png', class: 'image-profile') %>
			</div>
			<div class="col-2">
				<%= link_to(pessoas_editar_perfil_path, class: 'btn btn-purple btn-circle') do %>
					<i class="fa fa-pencil"></i>
				<% end %>
			</div>
		</div>

		<div class="container-info">

			<h1 class="info-apelido">
				<%= @pessoa.apelido %> 
			</h1>

			<h2 class="info-nome">
				<%= @pessoa.nome %> 
			</h2>

			<div class="row">
				<div class="col-12 container-label">
					<div class="row">
						<div class="col-4" style="padding-right: 0;">
							<p class="label-attr"> Matricula</p> 
						</div>
						<div class="col-8 text-right"  style="padding-left: 0;">
							<p class="label-info"><%= @pessoa.matricula %></p> 
						</div>
					</div>
					<hr>
				</div>

				<div class="col-12 container-label">
					<div class="row">
						<div class="col-4" style="padding-right: 0;">
							<p class="label-attr"> Curso</p> 
						</div>
						<div class="col-8 text-right"  style="padding-left: 0;">
							<p class="label-info"><%=  @pessoa.curso.nome %></p> 
						</div>
					</div>
					<hr>
				</div>

				<div class="col-12 container-label">
					<div class="row">
						<div class="col-4" style="padding-right: 0;">
							<p class="label-attr"> Campus</p> 
						</div>
						<div class="col-8 text-right"  style="padding-left: 0;">
							<p class="label-info"><%= @pessoa.campu.nome %></p> 
						</div>
					</div>
					<hr>
				</div>

				<div class="col-12 container-label">
					<div class="row">
						<div class="col-4" style="padding-right: 0;">
							<p class="label-attr"> Contato</p> 
						</div>
						<div class="col-8 text-right"  style="padding-left: 0;">
							<p class="label-info"><%= @pessoa.contato %></p> 
						</div>
					</div>
					<hr>
				</div>
			</div>

			<div class="row">
				<div class="col-12" style="margin-top: 40px;">
					<div class="row">

						<div class="col-5 container-hours-left">
							<p class="label-hours">
								<span class="label-time"> <%= (!@horas_realizadas.blank?) ? @horas_realizadas.to_s.gsub('.',',') : '0' %> horas </span> 
								<span class="label-complete"> realizadas </span> 
							</p>
						</div>

						<div class="col-1 container-hours-center">
							<div class="line-vertical"></div>
						</div>

						<div class="col-5 container-hours-right">
							<p class="label-hours">
								<span class="label-time"> <%= (!@horas_totais.blank?) ? @horas_totais.to_s.gsub('.',',') : '0' %> horas </span> 
								<span class="label-complete"> necessárias </span> 
							</p>
						</div>

					</div>
				</div>
			</div>

			<div class="row">
				<div class="col-12 container-sign-out">
					<%= link_to(destroy_usuario_session_path, method: :delete, class: 'bn btn-purple-inverse') do %>
                    	SAIR <i class="fa fa-sign-out"></i>
                    <% end %>
				</div>
			</div>

		</div>
	</div>
</div>

<%= stylesheet_link_tag 'pessoas' %>
<%= javascript_include_tag 'pessoas' %>

<script type="text/javascript">
	<% if !flash[:notice].blank? %>
		alertComplete("<%= flash[:notice] %>");
	<% end %>
</script>