config/routes.rb
Rails.application.routes.draw do
  resources :horas_complementares do
    collection do 
      get 'carregar_atividades_categoria'
    end
  end
  # get 'horas_complementares/index'
  # post 'horas_complementares/create'
  # post 'horas_complementares/update'
  get 'pessoas/index'
  get 'pessoas/cadastro_final'
  get 'pessoas/perfil'
  get 'pessoas/editar_perfil'
  post 'pessoas/cadastrar'
  post 'pessoas/editar'
  resources :pessoas do
  end

  get 'atividades/index'

  get 'categorias/index'

  get 'cursos/index'

  get 'campus/index'

  get 'dashboards/index'
  get 'dashboards/categoria'
  get 'dashboards/download_anexo'
  get 'dashboards/deletar_hora_complementar'

  devise_for :usuarios
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'dashboards#index'
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
	def index
		pessoa = Pessoa.find(session[:pessoa])
		total_horas = pessoa.curso.carga_atividades_complementares 
		total_realizadas = HorasComplementar.where(pessoa_id: pessoa.id, ativo: true).sum('quantidade_horas')

		# Percentual de Horas Realizadas
		@percentual_horas_complementares = HorasComplementar.percentual_horas_realizadas(total_realizadas, total_horas)

		# Informações das Categorias [Id, Categoria, Quantidade de Horas Totais, Quantidade de Horas Realizadas]
		@categorias_horas_realizadas_limite = HorasComplementar.categorias_horas_realizadas_limite(pessoa.id)
	end

	def categoria
		@categoria = Categoria.find(params[:categoria])

		# Informações da Categoria [Id, Categoria, Quantidade de Horas Totais, Quantidade de Horas Realizadas]
		@categoria_horas_realizadas_limite = HorasComplementar.categoria_horas_realizadas_limite(session[:pessoa], @categoria.id)

		# Percentual de Horas Realizadas na Categoria
		@percentual_categoria = Categoria.percentual_horas_realizadas(@categoria_horas_realizadas_limite[0][3], @categoria_horas_realizadas_limite[0][2])
		
		@horas_complementares = HorasComplementar.where(ativo: true, pessoa_id: session[:pessoa], categoria_id: @categoria.id).order(:created_at)
	end

	def download_anexo
		begin 
			anexo = HorasComplementar.caminho_anexo(params[:hora_complementar])
			send_file(anexo)
		rescue
			flash[:notice] = 'Poxa... Ocorreu algum problema com seu anexo, entre em contato com o suporte.'
			redirect_to dashboards_index_path
		end
	end

	def deletar_hora_complementar
		hora_complementar = HorasComplementar.find(params[:hora_complementar])
		hora_complementar.update(ativo: false)

		redirect_to dashboards_categoria_path(categoria: params[:categoria])
	end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/categoria.html.erb
<div class="container-default">
	<div class="container-header">
		<div class="row">
			<div class="col-1 col-sm-2" style="padding: 0; padding-left: 3%;">
				<%= link_to(dashboards_index_path, class: 'link-back') do %>
					<i class="fa fa-arrow-left icon-size"> </i>
				<% end %>
			</div>
			<div class="col-11 col-sm-10" style="padding: 0;">
				<h2 class="header-link"> Categoria <%= @categoria.numero %> </h2>
			</div>
		</div>
	</div>
	<div class="container-body">
		<div class="grafico">
			<div id="graficoCategoria"></div>
		</div>

		<div class="container-description">
			<h2><%= @categoria.nome %> <span>(<%= @categoria.limite_carga_horaria %>h)</span></h2>
		</div>

		<div class="container-list categoria">
			<% if @horas_complementares.blank? %>
				<center>
				<%= image_tag('open-box.png', style: 'width: 80px; height: 80px; margin-top: 0px;')%>
				</center>
				<p class="label-horas" style="font-size: 14px; margin-top: 10px; padding-left: 10px; color: #838383" align="center">Nenhuma hora complementar cadastrada ainda...</p>
			<% end %>
			<% @horas_complementares.each.with_index(1) do |hora_complementar,i| %>
				<div class="container-item">
					<div class="row">
						<div class="col-4" style="padding-right: 0;">
							<p class="label-horas" style="padding-top: 23px; padding-left: 10px;">
								<%= hora_complementar.quantidade_horas.to_s.gsub('.',',') %>h
							</p>
						</div>
						<div class="col-6" style="padding-left: 0; padding-right: 0;">
							<p class="label-categoria" style="padding-top: 17px; padding-right: 5px; margin: 0;">
								<%= (!hora_complementar.atividade.blank?) ? hora_complementar.atividade.nome : '' %>
							</p>
							<p class="label-descricao" style="padding-top: 3px; padding-right: 5px;">
								<%= hora_complementar.descricao %>
							</p>
						</div>
						<div class="col-2" style="padding: 0; padding-left: 10px;">
							<div class="dropdown" style="padding-top: 23px;">
								<a href="#" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="width: 40px;">
									<i class="fa fa-ellipsis-v" style="font-size: 20px; color: #838383; opacity: 0.8;"></i>
								</a>
								<div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton" style="margin: 0; padding: 0;">
									<% if !hora_complementar.anexo.blank? %>
										<%= link_to(dashboards_download_anexo_path(hora_complementar: hora_complementar.id), class: 'dropdown-item link-dropdown', target: '_blank') do %>
											Download do anexo
										<% end %>
										<hr style="margin-top: 2px; margin-bottom: 2px;">
									<% end %>
									<%= link_to(dashboards_deletar_hora_complementar_path(hora_complementar: hora_complementar.id, categoria: hora_complementar.categoria.id), class: 'dropdown-item link-dropdown delete') do %>
										Excluir
									<% end %>
								 </div>
							</div>
						</div>
					</div>
				</div>
			<% end %>
		</div>
	</div>
</div>

<%= stylesheet_link_tag 'dashboards' %>
<%= javascript_include_tag 'dashboards' %>

<script type="text/javascript">
	var chart = c3.generate({
        bindto: '#graficoCategoria',
        data:{
            columns: [
                ['%', 0]
            ],

            type: 'gauge'
        },
        color: {
            pattern: ['#b275f4', '#efefef']

        },
	    gauge: {
	      width: 25
	    }
    });

    setTimeout(function () {
    	chart.load({
        	columns: [['%', <%= @percentual_categoria %>]]
    	});
	}, 300);

	<% if !flash[:notice].blank? %>
		alertComplete("<%= flash[:notice] %>");
	<% end %>
</script>

app/views/dashboards/index.html.erb
<div class="container-default">
	<div class="container-header">
		<div class="row">
			<div class="col-12 col-sm-12">
				<h2> Dashboard </h2>
			</div>
		</div>
	</div>
	<div class="container-body">
		<div class="grafico">
			<div id="graficoGeral"></div>
		</div>

		<div class="container-list">
			<% if @categorias_horas_realizadas_limite.blank? %>
				<center>
				<%= image_tag('open-box.png', style: 'width: 80px; height: 80px; margin-top: 30px;')%>
				</center>
				<p class="label-horas" style="font-size: 14px; margin-top: 10px; padding-left: 10px; color: #838383" align="center">Nenhuma categoria cadastrada para este curso...</p>
			<% end %>
			<% @categorias_horas_realizadas_limite.each.with_index(1) do |categoria,i| %>
				<%= link_to(dashboards_categoria_path(categoria: categoria[0]), style: 'text-decoration: none;') do %>
					<div class="container-item">
						<div class="row">
							<div class="col-4" style="padding-right: 0;">
								<canvas id="canvas<%= i %>" height="60" width="60" style="max-width: 162px !important; margin-top: 10px; margin-left: 8px;"></canvas>
							</div>
							<div class="col-8" style="padding-left: 0;">
								<p class="label-categoria" style="padding-top: 25px; padding-right: 5px;">
									<%= categoria[1] %>
								</p>
							</div>
						</div>
					</div>
				<% end %>
			<% end %>
		</div>
	</div>
</div>

<%= stylesheet_link_tag 'dashboards', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'dashboards', 'data-turbolinks-track': 'reload' %>

<script type="text/javascript">
	var chart = c3.generate({
        bindto: '#graficoGeral',
        data:{
            columns: [
                ['%', 0]
            ],

            type: 'gauge'
        },
        color: {
            pattern: ['#b275f4', '#efefef']

        },
	    gauge: {
	      width: 25
	    }
    });

    setTimeout(function () {
    	chart.load({
        	columns: [['%', <%= @percentual_horas_complementares %>]]
    	});
	}, 300);

    <% @categorias_horas_realizadas_limite.each.with_index(1) do |categoria,i| %>

		Chart.types.Doughnut.extend({
		    name: "Doughtnut1",
		    showTooltip: function() {
		        this.chart.ctx.save();
		        Chart.types.Doughnut.prototype.showTooltip.apply(this, arguments);
		        this.chart.ctx.restore();
		    },
		    draw: function() {
		        Chart.types.Doughnut.prototype.draw.apply(this, arguments);

		        var width = this.chart.width,
		            height = this.chart.height;

		        var fontSize = (height / 75).toFixed(2);
		        this.chart.ctx.font = fontSize + "em sans-serif";
		        this.chart.ctx.textBaseline = "middle";
		        this.chart.ctx.fillStyle = "#838383"
		        var text = "<%= categoria[3].round(1) %>h",
		            textX = Math.round((width - this.chart.ctx.measureText(text).width) / 2),
		            textY = height / 2;

		        this.chart.ctx.fillText(text, textX, textY);
		    }
		});

		var canvas = document.getElementById("canvas<%= i %>");
		var ctx = canvas.getContext("2d");

		ctx.width = 118;
		ctx.height = 118;


		var data = [{
		    value: <%= categoria[3].round(1) %>,
		    color: "#b275f4"
		},{
		    value: <%= categoria[2].round(1) %>-<%= categoria[3].round(1) %>,
		    color: "#efefef"
		}];

		var Doughtnut1Chart = new Chart(ctx).Doughtnut1(data, {
		    // responsive: true,
		    percentageInnerCutout: 75,
		    maintainAspectRatio: false,
		    segmentShowStroke: false
		});
	<% end %>

	<% if !flash[:notice].blank? %>
		alertComplete("<%= flash[:notice] %>");
	<% end %>
</script>