config/routes.rb
Rails.application.routes.draw do
  resources :horas_complementares do
    collection do 
      get 'carregar_atividades_categoria'
    end
  end
  # get 'horas_complementares/index'
  # post 'horas_complementares/create'
  # post 'horas_complementares/update'
  get 'pessoas/index'
  get 'pessoas/cadastro_final'
  get 'pessoas/perfil'
  get 'pessoas/editar_perfil'
  post 'pessoas/cadastrar'
  post 'pessoas/editar'
  resources :pessoas do
  end

  get 'atividades/index'

  get 'categorias/index'

  get 'cursos/index'

  get 'campus/index'

  get 'dashboards/index'
  get 'dashboards/categoria'
  get 'dashboards/download_anexo'
  get 'dashboards/deletar_hora_complementar'

  devise_for :usuarios
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'dashboards#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/atividade.rb
class Atividade < ApplicationRecord
  belongs_to :categoria
end

app/models/campu.rb
class Campu < ApplicationRecord
end

app/models/categoria.rb
class Categoria < ApplicationRecord
  belongs_to :curso

  	def self.percentual_horas_realizadas(horas_realizadas, total_horas)
	  	percentual = 0
	  	if !total_horas.blank? && total_horas > 0
			percentual = (horas_realizadas/total_horas)*100
		end
		return percentual
	end
end

app/models/curso.rb
class Curso < ApplicationRecord
  belongs_to :campu
  has_many :categorias
end

app/models/horas_complementar.rb
class HorasComplementar < ApplicationRecord
  belongs_to :categoria
  belongs_to :atividade

  mount_uploader :anexo, AnexoUploader


  def self.categorias_horas_realizadas_limite(pessoa_id)
  	pessoa = Pessoa.find(pessoa_id)
  	categorias = pessoa.curso.categorias.where(ativo: true).order(:nome)
  	categorias_horas = Array.new

  	categorias.each do |categoria|
  		categorias_horas.push([categoria.id, categoria.nome, categoria.limite_carga_horaria, quantidade_horas_realizadas_categoria(pessoa.id, categoria.id)])
  	end

  	return categorias_horas
  end

  def self.quantidade_horas_realizadas_categoria(pessoa_id, categoria_id)
  	horas_complementares = self.where(ativo: true, pessoa_id: pessoa_id, categoria_id: categoria_id).sum('quantidade_horas')
  	
  	return horas_complementares
  end

  def self.categoria_horas_realizadas_limite(pessoa_id, categoria_id)
    categoria_horas = Array.new
    categoria = Categoria.find(categoria_id)
    categoria_horas.push([categoria.id, categoria.nome, categoria.limite_carga_horaria, quantidade_horas_realizadas_categoria(pessoa_id, categoria.id)])
    return categoria_horas
  end

  def self.percentual_horas_realizadas(horas_realizadas, total_horas)
    percentual = 0
    if !total_horas.blank? && total_horas > 0
      percentual = (horas_realizadas/total_horas)*100
    end
    return percentual
  end

  def self.caminho_anexo(hora_complementar)
    hora_complementar = HorasComplementar.find(hora_complementar)
    if hora_complementar.anexo.file.exists?
      caminho = File.join(Rails.root, 'public', hora_complementar.anexo.url)
      return caminho
    else
      return nil
    end
  end

  def self.validar_horas_realizadas_categoria(quantidade_horas, categoria, pessoa)
    categoria = Categoria.find(categoria)
    horas_realizadas = HorasComplementar.where(ativo: true, pessoa_id: pessoa, categoria_id: categoria).sum('quantidade_horas')
    if horas_realizadas + quantidade_horas <= categoria.limite_carga_horaria
      return true
    else
      return false
    end
  end
end

app/models/pessoa.rb
class Pessoa < ApplicationRecord
  belongs_to :campu
  belongs_to :curso
  belongs_to :usuario
  has_many :horas_complementares
  
  validates_uniqueness_of :matricula, conditions: -> { where(ativo: true) }

  mount_uploader :foto, FotoUploader

end

app/models/usuario.rb
class Usuario < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/atividades_controller.rb
class AtividadesController < ApplicationController
  def index
  end
end

app/controllers/campus_controller.rb
class CampusController < ApplicationController
  def index
  end
end

app/controllers/categorias_controller.rb
class CategoriasController < ApplicationController
  def index
  end
end

app/controllers/cursos_controller.rb
class CursosController < ApplicationController
  def index
  end
end

app/controllers/pessoas_controller.rb
class PessoasController < ApplicationController
  def index
  end

  def cadastro_final
    if !session[:pessoa].blank?
      flash[:notice] = 'Você já completou seu cadastro!'
      redirect_to pessoas_perfil_path
    else
    	@cursos = Curso.where(ativo: true).order(:nome)
      render layout: 'empty'
    end
  end

  def cadastrar
    @cursos = Curso.where(ativo: true).order(:nome)

  	@pessoa = Pessoa.new
  	@pessoa.nome = params[:nome]
  	@pessoa.apelido = params[:apelido]
  	@pessoa.matricula = params[:matricula]
  	@pessoa.curso_id = params[:curso]
    @pessoa.campu_id = Curso.find(params[:curso]).campu.id
  	@pessoa.contato = params[:contato]
  	@pessoa.usuario_id = current_usuario.id
  	@pessoa.foto = params[:foto]
  
  	if @pessoa.save
      session[:pessoa] = @pessoa.id
      redirect_to dashboards_index_path
    else
      flash[:notice] = 'Número de matricula já existente'
      redirect_to pessoas_cadastro_final_path
    end
  
  end

  def perfil
    @pessoa = Pessoa.find(session[:pessoa])
    @horas_realizadas = @pessoa.horas_complementares.where(ativo: true).sum('quantidade_horas')
    @horas_totais = @pessoa.curso.carga_atividades_complementares
  end

  def editar_perfil
    @pessoa = Pessoa.find(session[:pessoa])
    @cursos = Curso.where(ativo: true).order(:nome)
  end

  def show
  end

  def update
    pessoa = Pessoa.find(session[:pessoa])
    pessoa.update(nome: params[:pessoa][:nome], apelido: params[:pessoa][:apelido], matricula: params[:pessoa][:matricula], curso_id: params[:pessoa][:curso], campu_id: Curso.find(params[:pessoa][:curso]).campu_id, contato: params[:pessoa][:contato], foto: params[:pessoa][:foto])
    flash[:notice] = 'Perfil atualizado com sucesso!'
    redirect_to pessoas_perfil_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/atividade_helper.rb
module AtividadeHelper
end

app/helpers/campus_helper.rb
module CampusHelper
end

app/helpers/categorias_helper.rb
module CategoriasHelper
end

app/helpers/curso_helper.rb
module CursoHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/pessoa_helper.rb
module PessoaHelper
end

app/views/layouts/_menu.html.erb
<div class="menu-horizontal">
	<div class="options">
		<div class="row">
		
			<div class="col-4 options-left">
				<%=link_to(dashboards_index_path, class: 'option-item') do %>
					<i class="fa fa-calendar-check-o" style="font-size: 23px; margin-top: 10px;"></i>
				<% end %>
			</div>

			<div class="col-4 options-center">
				<%=link_to(horas_complementares_path, class: 'option-item') do %>
					<i class="fa fa-pencil-square" style="font-size: 35px; "></i>
				<% end %>
			</div>

			<div class="col-4 options-right">
				<%=link_to(pessoas_perfil_path, class: 'option-item') do %>
					<i class="fa fa-user-o" style="font-size: 23px; margin-top: 10px;"></i>
				<% end %>
			</div>

		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <meta charset="utf-8">        
    <meta http-equiv="X-UA-compatible", content="ie-edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>Completar - Gerenciador de Horas Complementares</title>
    <%= favicon_link_tag image_path('logo-azul.png') %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://cdn.rawgit.com/plentz/jquery-maskmoney/master/dist/jquery.maskMoney.min.js', 'data-turbolinks-track': 'reload' %>
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.10/jquery.mask.js"></script> -->
    <link rel="manifest" href="/manifest.json" />
    <meta name="apple-mobile-web-app-capable" content="yes"></head>

  <body>

    <div id="preloader">
      <div class="inner">
        <div class="balls">
          <div></div>
          <div></div>
          <div></div>                    
        </div>
      </div>
    </div>

    <%= yield %>
    <%= render 'layouts/menu' %>
  </body>
</html>

app/views/layouts/devise.erb
<!DOCTYPE html>
<html>

    <head>
        <meta charset="utf-8">        
        <meta http-equiv="X-UA-compatible", content="ie-edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
        <title>Completar - Gerenciador de Horas Complementares</title>
        <%= favicon_link_tag image_path('logo-azul.png') %>
        
        <%= csrf_meta_tags %>
        
        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

        <%= stylesheet_link_tag 'devise', media: 'all', 'data-turbolinks-track' => true %>
    </head>

    <body>
        <div class="background-default">
            <div class="container-auth">
                <%= yield %>
                <%= yield :javascript %>    
            </div>
        </div>
    </body>
</html>     

app/views/layouts/empty.html.erb
<!DOCTYPE html>
<html>

  <head>
    <meta charset="utf-8">        
    <meta http-equiv="X-UA-compatible", content="ie-edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>Completar - Gerenciador de Horas Complementares</title>
    <%= favicon_link_tag image_path('logo-azul.png') %>
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.10/jquery.mask.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>